version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
  - package-ecosystem: docker
    directories:
      - /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
